import os
import glob
import json
import random
import subprocess
from groq import Groq
from faster_whisper import WhisperModel
import datetime

# Setup
PIPER_MODEL = os.path.join("voice", "en_GB-northern_english_male-medium.onnx")
RAW_FOOTAGES_DIR = "raw footages"

def get_next_folder():
    base_dir = os.getcwd()
    i = 1
    while True:
        folder_name = f"short{i}"
        folder_path = os.path.join(base_dir, folder_name)
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            return folder_path
        i += 1

def generate_script(raw_thought, api_key):
    client = Groq(api_key=api_key)
    
    system_prompt = """You are an AI scriptwriter for a short-form video page that narrates human inner thoughts.
Your task is to transform a RAW THOUGHT into a ~45 second script designed for Instagram Reels / TikTok.
The tone must be introspective, relatable, calm, reflective, simple language.
NOT poetic quotes page, NOT cringe or overly dramatic, sound like a quiet late-night voice note.
The script must feel like an AI narrating a human inner monologue.

SCRIPT STRUCTURE (MANDATORY)
1. Hook (2-3 seconds): 1 short punchy sentence.
2. Main Reflection (30-35 sec): Expand the raw thought into a relatable reflection. Use second person occasionally ("you"). Keep sentences short.
3. Closing Question (last 3-5 sec): End with a simple question to drive comments. 1 sentence.

CAPTION RULES
Generate a short caption: 1-2 lines max, lowercase, reflective tone, no hashtags, no emojis.

OUTPUT FORMAT (STRICT JSON)
{
  "hook": "...",
  "script": "...",
  "question": "...",
  "caption": "..."
}
"""
    completion = client.chat.completions.create(
        model="llama3-8b-8192", # Fast and capable enough for this
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"RAW_THOUGHT: {raw_thought}"}
        ],
        temperature=0.7,
        response_format={"type": "json_object"}
    )
    
    response_text = completion.choices[0].message.content
    return json.loads(response_text)

def generate_audio(text, output_path):
    command = [
        "piper",
        "--model", PIPER_MODEL,
        "--output_file", output_path
    ]
    # Running piper using subprocess and piping the text to stdin
    subprocess.run(command, input=text.encode('utf-8'), check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def format_ass_time(seconds):
    # .ass format: D:HH:MM:SS.XX
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centisecs = int(round((seconds - int(seconds)) * 100))
    if centisecs == 100:
        secs += 1
        centisecs = 0
    return f"{hours}:{minutes:02d}:{secs:02d}.{centisecs:02d}"

def process_subtitles(audio_path, output_ass_path):
    # Load fast whisper (tiny is very fast and words are usually clear generated by TTS)
    model = WhisperModel("tiny.en", device="cpu", compute_type="int8")
    
    segments, info = model.transcribe(audio_path, word_timestamps=True)
    
    # Create ASS content
    ass_lines = [
        "[Script Info]",
        "ScriptType: v4.00+",
        "PlayResX: 1080",
        "PlayResY: 1920",
        "WrapStyle: 1",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        "Style: Default,Impact,130,&H0000E6FF,&H000000FF,&H00000000,&H99000000,-1,0,0,0,100,100,0,0,1,12,5,5,30,30,800,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    ]
    
    words = []
    for segment in segments:
        for word in segment.words:
            words.append({"word": word.word.strip(), "start": word.start, "end": word.end})
            
    # Group words in chunks of 2-3 for punchy subtitles
    chunk_size = 2
    for i in range(0, len(words), chunk_size):
        chunk = words[i:i + chunk_size]
        if not chunk: continue
        start_time = format_ass_time(chunk[0]["start"])
        end_time = format_ass_time(chunk[-1]["end"])
        text = " ".join([w["word"] for w in chunk]).upper()
        
        ass_lines.append(f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{text}")
        
    with open(output_ass_path, "w", encoding="utf-8") as f:
        f.write("\n".join(ass_lines))

def get_random_video():
    videos = glob.glob(os.path.join(RAW_FOOTAGES_DIR, "*.mp4"))
    if not videos:
        return None
    return random.choice(videos)

def build_final_video(bg_video, audio_path, ass_path, output_video):
    # Escaping paths for ffmpeg filter
    ass_escaped = ass_path.replace('\\', '/').replace(':', '\\:')
    
    command = [
        "ffmpeg",
        "-y",
        "-i", bg_video,
        "-i", audio_path,
        "-filter_complex", 
        f"[0:v]loop=loop=-1:size=2:start=0,setpts=N/FRAME_RATE/TB,crop=ih*9/16:ih,scale=1080:1920,subtitles='{ass_escaped}'[v]",
        "-map", "[v]",
        "-map", "1:a",
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        "-shortest", # End when audio ends
        output_video
    ]
    
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def generate_short(raw_thought, update_status):
    from dotenv import load_dotenv
    load_dotenv()
    
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your_groq_api_key_here":
        raise ValueError("GROQ_API_KEY not found in .env")
        
    bg_video = get_random_video()
    if not bg_video:
        raise FileNotFoundError("No raw footages found in the 'raw footages' directory.")

    output_dir = get_next_folder()
    
    # 1. Script Generation
    update_status("Generating script...", 20)
    data = generate_script(raw_thought, api_key)
    full_text = f"{data['hook']} {data['script']} {data['question']}"
    
    # Save script text
    with open(os.path.join(output_dir, "script_output.txt"), "w", encoding="utf-8") as f:
        f.write(json.dumps(data, indent=2))
        
    # 2. Audio Generation
    update_status("Generating voiceover with Piper TTS...", 40)
    audio_path = os.path.join(output_dir, "voiceover.wav")
    generate_audio(full_text, audio_path)
    
    # 3. Subtitles
    update_status("Generating subtitles with Whisper...", 60)
    ass_path = os.path.join(output_dir, "subtitles.ass")
    process_subtitles(audio_path, ass_path)
    
    # 4. Final Video Assembly
    update_status("Assembling final video with FFmpeg...", 80)
    final_video = os.path.join(output_dir, "final.mp4")
    build_final_video(bg_video, audio_path, ass_path, final_video)
    
    update_status("Done!", 100)
    
    return {
        "folder": output_dir,
        "video_path": final_video,
        "caption": data['caption']
    }
